// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfeumekzcfoumdhqvvrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmZXVtZWt6Y2ZvdW1kaHF2dnJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwODM4MTEsImV4cCI6MjA2MDY1OTgxMX0.TKlIL0W4OunMCxOCysZFx9lnIMlly3yz_wGyMcmVL8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);